# This workflow template runs:
#   - a tox container with tests
#   - a service container (eg. a database) to be used by tox tests.

name: Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test-pre-commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v2

      - name: Run commit hooks.
        run: |
          pip3 --no-cache-dir install pre-commit
          git --version
          pre-commit run -a
